# Generated by Django 4.2.4 on 2023-08-10 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='from date')),
                ('to_date', models.DateField(verbose_name='to date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('cancel', 'Cancel')], default='pending', max_length=10, verbose_name='status')),
                ('reason', models.TextField(verbose_name='reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
