# Generated by Django 4.2.4 on 2023-08-16 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20, unique=True, verbose_name='project ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='project name')),
                ('project_start_date', models.DateField(verbose_name='project start date')),
                ('project_end_date', models.DateField(verbose_name='project end date')),
                ('description', models.TextField(verbose_name='description')),
                ('leader_name', models.CharField(max_length=50, verbose_name='leader name')),
                ('client_name', models.CharField(max_length=100, verbose_name='client name')),
                ('technology', models.CharField(max_length=50, verbose_name='technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'work allocation',
                'verbose_name_plural': 'work allocations',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='from date')),
                ('to_date', models.DateField(verbose_name='to date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('cancel', 'Cancel')], default='pending', max_length=10, verbose_name='status')),
                ('reason', models.TextField(verbose_name='reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
